version: "3.5"

services:
  # Install postgres and setup the student database.
  postgres:
    container_name: postgres-debezium
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
